### ISSUE TITLE
Garbled image on the 168x144 display

### ISSUE THREAD

**Issue by deshipu** [adafruit/Adafruit_CircuitPython_SharpMemoryDisplay#3]
I tested this with Feather M4, and while the 96x96 display works perfectly, the 168x144 one, connected the same way, displays garbage:
![img_20181223_185405](https://user-images.githubusercontent.com/1181357/50386320-9003f780-06e4-11e9-87f8-b4b13aee432e.jpg)

**Comment by deshipu** [comment]
I did change the line that creates the display object:

```python
display = adafruit_sharpmemorydisplay.SharpMemoryDisplay(spi, scs, 168, 144)
```

**Comment by deshipu** [comment]
Ok, swapping width and height helps:
```python
display = adafruit_sharpmemorydisplay.SharpMemoryDisplay(spi, scs, 144, 168)
```

**Comment by ladyada** [comment]
ok please add a line in the example that is commented out to demonstrate it!
